name: Lint and Format

on:
  push:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install --global htmlhint csslint prettier

      - name: Run HTML linting
        run: htmlhint .

      - name: Run CSS linting
        run: csslint .

      - name: Format code with Prettier
        run: prettier --write .

      - name: Commit formatted code
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "Your GitHub Email"
          git add .
          git commit -m "Format code with Prettier" || echo "No changes to commit"
