name: Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install --global htmlhint csslint

      - name: Run HTML linting
        run: htmlhint .

      - name: Run CSS linting
        run: csslint .
